import { getProjectDirs } from "./locations.js";
import fs from 'fs';
import path from 'path';
import { blueRailroadContractAddress, blueRailroadV2ContractAddress } from './constants.js';
import { bytes32ToCid } from './cid_utils.js';

// Song mapping for Blue Railroad Train challenge
// Maps songId to track information from the album
const BLUE_RAILROAD_SONGS = {
    0: { title: "Blue Railroad Train", artist: "Tony Rice" },
    1: { title: "Church Street Blues", artist: "Tony Rice" },
    2: { title: "Me and My Guitar", artist: "Tony Rice" },
    3: { title: "Shadows of the Past", artist: "Tony Rice" },
    4: { title: "Streets of London", artist: "Tony Rice" },
    5: { title: "Song for Life", artist: "Tony Rice" },
    6: { title: "Old Train", artist: "Tony Rice" },
    7: { title: "Fare Thee Well", artist: "Tony Rice" },
};

/**
 * Verifies that all Blue Railroad video files exist and returns sorted metadata
 * @returns {Promise<Array>} Sorted metadata entries in reverse chronological order
 * @throws {Error} If metadata file is missing or if any video files are missing
 */
export async function verifyBlueRailroadVideos() {
    const { fetchedAssetsDir } = getProjectDirs();
    const chainId = '10';
    const metadataPath = path.join(fetchedAssetsDir, `${chainId}-${blueRailroadContractAddress}.json`);

    if (!fs.existsSync(metadataPath)) {
        throw new Error(
            'Blue Railroad metadata not found! Please run:\n' +
            'npm run fetch-video-metadata\n' +
            'npm run download-videos'
        );
    }

    const metadata = JSON.parse(fs.readFileSync(metadataPath));
    const missingVideos = [];

    for (const [tokenId, data] of Object.entries(metadata)) {
        if (!data.video_url) continue; // Skip entries without videos

        const expectedVideoPath = path.join(
            fetchedAssetsDir,
            `${chainId}-${blueRailroadContractAddress}-${tokenId}.mp4`
        );

        if (!fs.existsSync(expectedVideoPath)) {
            missingVideos.push(tokenId);
        }
    }

    if (missingVideos.length > 0) {
        throw new Error(
            `Missing videos for tokens: ${missingVideos.join(', ')}\n` +
            'Please run: npm run download-videos'
        );
    }

    // Return the metadata object (keeping original structure)
    return metadata;
}

/**
 * Generate ERC721 metadata JSON files for Blue Railroad V2 tokens
 * Writes files to {outputDir}/meta/bluerailroad/{tokenId}
 * @param {Object} blueRailroadV2s - V2 token data from chain_reading.getBlueRailroadV2s()
 * @param {string} outputDir - Site output directory
 */
export function generateBlueRailroadV2Metadata(blueRailroadV2s, outputDir) {
    if (!blueRailroadV2s || Object.keys(blueRailroadV2s).length === 0) {
        console.log('No Blue Railroad V2 tokens to generate metadata for');
        return;
    }

    console.time('Blue Railroad V2 Metadata');

    // Create output directory
    const metadataDir = path.join(outputDir, 'meta', 'bluerailroad');
    if (!fs.existsSync(metadataDir)) {
        fs.mkdirSync(metadataDir, { recursive: true, mode: 0o777 });
    }

    for (const [tokenId, token] of Object.entries(blueRailroadV2s)) {
        const songInfo = BLUE_RAILROAD_SONGS[token.songId] || {
            title: `Track ${token.songId}`,
            artist: "Tony Rice"
        };

        // Convert bytes32 videoHash back to IPFS CID
        const videoHashHex = token.videoHash;
        const videoCid = bytes32ToCid(videoHashHex);

        let imageUrl = '';
        let animationUrl = '';

        if (videoCid) {
            // Use proper IPFS CID URL format for video
            animationUrl = `ipfs://${videoCid}`;
            // Use PickiPedia thumbnail for image (generated by blue-railroad-import)
            // Filename format: Blue_Railroad_Video_{cid}.jpg
            imageUrl = `https://pickipedia.xyz/wiki/Special:FilePath/Blue_Railroad_Video_${videoCid}.jpg`;
        }

        const metadata = {
            name: `Blue Railroad Train #${tokenId}`,
            description: `Exercise completed to "${songInfo.title}" by ${songInfo.artist}. ` +
                `This Blue Railroad Train token represents a verified exercise session ` +
                `completed at Ethereum block ${token.blockheight.toLocaleString()}.`,
            image: imageUrl,
            animation_url: animationUrl,
            external_url: `https://cryptograss.live/blox-office/blue-railroad`,
            attributes: [
                {
                    trait_type: "Song",
                    value: songInfo.title
                },
                {
                    trait_type: "Artist",
                    value: songInfo.artist
                },
                {
                    trait_type: "Song ID",
                    value: token.songId,
                    display_type: "number"
                },
                {
                    trait_type: "Block Height",
                    value: token.blockheight,
                    display_type: "number"
                },
                {
                    trait_type: "Contract Version",
                    value: "V2"
                }
            ],
            properties: {
                songId: token.songId,
                blockheight: token.blockheight,
                videoHash: token.videoHash,
                contract: blueRailroadV2ContractAddress
            }
        };

        // Write metadata file (no .json extension - tokenURI expects bare path)
        const metadataPath = path.join(metadataDir, tokenId.toString());
        fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));

        console.log(`Generated metadata for Blue Railroad V2 #${tokenId}`);
    }

    console.timeEnd('Blue Railroad V2 Metadata');
    console.log(`Generated ${Object.keys(blueRailroadV2s).length} Blue Railroad V2 metadata files`);
}
